# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-20 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tovar',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
