# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-20 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20170920_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tovar',
            name='image',
            field=models.ImageField(blank=True, height_field=640, upload_to='/media/upload', width_field=360),
        ),
    ]
