# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-24 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20170920_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tovar',
            name='description',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
