# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-24 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20170924_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='tovar',
            name='image_mini',
            field=models.ImageField(blank=True, upload_to='upload/images/thumb/'),
        ),
        migrations.AlterField(
            model_name='tovar',
            name='image',
            field=models.ImageField(blank=True, upload_to='upload/images/'),
        ),
    ]
