# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-03 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20170924_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='tovar',
            name='haracteristiki',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
