# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-06 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_tovar_haracteristiki'),
    ]

    operations = [
        migrations.AddField(
            model_name='tovar',
            name='best',
            field=models.BooleanField(default=False),
        ),
    ]
